theme = "hugo-cactus-theme"
BaseURL = "localhost"
LanguageCode = "zh-CN"
Title = "生活中的难过"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-160743058-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "snowlyg-com"

[params]
	name = "Snowlyg"
	description = "不会偷懒的程序员--不是个好程序员"
	bio = "不会偷懒的程序员--不是个好程序员"
	# Enter optionally your twitter account
	twitter = "ld_snowlyg"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = "首页"
	subscribe = "订阅"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = "热文推荐"
	copyright = "© Copyright snowlyg 2020 "
	# Sharing options and author information in posts
	aboutAuthor = "一个纯粹的程序爱好者"
	tweet = ""
	share = "分享"
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "empty"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
    dribble  = "https://www.dribbble.com/"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"